### ISSUE TITLE
codeblocks overflow / nonscaling

### ISSUE THREAD

**Issue by MrCode97** [baloise/ws-itsec_owasp#9]
The code-blocks in the gitpitch presentation only do scale to a rather limited point. 
Meaning even though there is plenty of space around the code-blocks, they stop scaling at a certain point and you have to scroll to the left and right:
![image](https://user-images.githubusercontent.com/25118350/54988879-a22d5480-4fb7-11e9-8337-ffb015c44f0c.png)

A workaround is to "oversize" the block via custom css. This **will cause that the code-blocks overflow if the browser-window is too narrow.**
Example from PITCHME.css:
```css
.reveal pre {
    width: 130%;
    margin-inline-start: -15%;
    box-shadow : none;
}
```

Note: This has been reported and closed, here: gitpitch/gitpitch#200
I assumed that increasing the value of `maxScale` in `reveal.js ` might solve the issue but it did not when I tried it locally.
